name: ms-msother-mschassistypes (Update)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4.2.2
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/msother/mschassistypes.ps1
      - name: Submit a Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          commit-message: Updated Microsoft Windows chassis types JSON
          branch: au/ms-msother-mschassistypes
          delete-branch: true
          title: Automatic Update of Windows chassis types
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          