name: ms-mswin-update-lifecycle-server (Update)
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/mswin/lifecycle-server.ps1
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ steps.generate-token.outputs.token }}
          commit-message: Refresh mswin lifecycle-server.json with latest server OS lifecycle dates
          branch: au/ms-mswin-update-lifecycle-server
          delete-branch: true
          title: Refresh server OS lifecycle
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-url != ''
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}" --delete-branch
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"